resource "local_file" "pet" {
  filename = var.filename # Using variable for filename
  content = var.content # Using variable for content
  file_permission = "0744"
}

resource "local_file" "car" {
  filename = "car.txt"
  content = "BMW"
  file_permission = "0644"
}

resource "random_pet" "my_pet" {
  prefix = "my-"
  separator = "."
  length = 2
}

# Demonstrating resource linking using variable interpolation. 
# This resource creates a file that contains the name of the pet generated by the random_pet resource.
resource "local_file" "resource_linking" {
  filename = "resource_linking.txt"
  content = "My pet name is ${random_pet.my_pet.id}"
  depends_on = [ random_pet.my_pet ] # Ensures that the random_pet resource is created before this one. This explicit dependency is optional here as Terraform automatically infers it from the interpolation.
}

# we can use output variables to save expressions or values derived from other resources or variables.
output "pet_name" {
  value = random_pet.my_pet.id
  description = "Record the value of the pet ID generated by the random_pet resource"
}